FROM golang:1.18

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY ./cmd/store-server/private.pem ./private.pem
RUN go build -v -o /usr/local/bin/app ./cmd/store-server

CMD ["app"]

