FROM golang:1.18

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY ./cmd/store-client/messages.json ./messages.json

RUN go build -v -o /usr/local/bin/app ./cmd/store-client

CMD ["app"]

